name: service1

on:
  push:
    branches: [ main ]
    paths:
      - services/service1/**
      - libs/metrics/**
      - libs/security/**
      - .github/workflows/service1.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: service1